name: Demo Bug
description: File a bug in the official demo
labels:
  - "type:bug"
  - "domain: website"
body:
  - type: checkboxes
    attributes:
      label: Issue Checklist
      options:
        - label: I'm using the official demo at https://yume-chan.github.io/ya-webadb
          required: true
        - label: For Scrcpy related issues, I have searched in [Genymobile/scrcpy](https://github.com/Genymobile/scrcpy/issues) repository.
          required: true
  - type: input
    attributes:
      label: Runtime
      description: Operating system, runtime name and version
      placeholder: e.g. macOS 13.0, Chrome 105
    validations:
      required: true
  - type: input
    attributes:
      label: Device
      description: Device model and Android version
      placeholder: e.g. Pixel 5, Android 12
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      value: |
        1.
        2.
        3.
    validations:
      required: true
